language: cpp
os: linux
compiler: gcc

before_script:
  - sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev libglm-dev libglew-dev
  - mkdir build
  - cd build
  - cmake ..

script: make 

